import type { Metadata } from "next";
import Image from "next/image";
import {phone, text, SiteFooter, SiteHeader} from "../site-chrome";
export const metadata:Metadata={title:"Tree & Lawn Services | The Ciprians",description:"Tree cutting, lawn mowing, and tree care in Shelbyville, Kentucky from The Ciprians Tree Service.",alternates:{canonical:"/services"}};
const services=[
 {name:"Cutting down trees",copy:"Professional tree cutting for hazardous-tree concerns, construction or clearing needs, green-area maintenance, and risk prevention. The current business site emphasizes safe, efficient work and planning appropriate to the property.",fit:"Start with a property review so the tree, access, and surrounding space can be understood."},
 {name:"Lawn mowing",copy:"Mowing and routine lawn care for homes, businesses, and public-facing outdoor spaces that need a clean, consistent, maintained finish.",fit:"Useful for properties that need dependable upkeep rather than a one-time cosmetic pass."},
 {name:"Tree care",copy:"Pruning, fertilization, pest-control attention, and general tree-health assessment intended to keep trees safer, healthier, and visually balanced.",fit:"A practical starting point when the tree should be preserved but needs informed attention."},
] as const;
export default function ServicesPage(){return <main><a className="skip" href="#main">Skip to content</a><SiteHeader/><section className="cip-subhero" id="main"><div><p className="eyebrow">What the crew handles</p><h1>Work shaped<br/>around the land.</h1><p>Tree and lawn services should begin with the actual property—not a one-size-fits-all package.</p><div className="actions"><a className="button primary" href={phone}>Request a free estimate</a><a className="button line" href={text}>Text the crew</a></div></div><div className="cip-subhero-photo"><Image src="/images/tree-care.jpg" alt="Green tree in a maintained landscape, from The Ciprians current website" fill priority unoptimized sizes="(max-width:900px) 100vw, 50vw"/></div></section><section className="cip-service-list">{services.map((service,i)=><article key={service.name}><b>0{i+1}</b><div><p className="eyebrow">Service</p><h2>{service.name}</h2><p>{service.copy}</p><small>{service.fit}</small></div><a href={phone}>Discuss the property →</a></article>)}</section><section className="cip-callout"><p className="eyebrow">Shelbyville, Kentucky</p><h2>See something that needs attention?</h2><p>Send a text or call with what you are seeing. The next step is a practical conversation about the property and the work.</p><a className="button primary" href={text}>Text 502-692-8014</a></section><SiteFooter/></main>}
